In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import regex as re
from sklearn.preprocessing import LabelEncoder

# PREPROCESSING

In [2]:
df = pd.read_csv('depi.csv')

/var/folders/rd/rm1ghq0950j6l712s6ykcc5w0000gn/T/ipykernel_78572/2927016486.py:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('depi.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80511 entries, 0 to 80510
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name                         80511 non-null  object
 1   Financial Status             24894 non-null  object
 2   Paid at                      15806 non-null  object
 3   Fulfillment Status           24894 non-null  object
 4   Fulfilled at                 14829 non-null  object
 5   Currency                     24894 non-null  object
 6   Subtotal                     24894 non-null  float64
 7   Shipping                     24894 non-null  float64
 8   Taxes                        24894 non-null  float64
 9   Total                        24894 non-null  float64
 10  Discount Amount              24894 non-null  float64
 11  Shipping Method              23678 non-null  object
 12  Created at                   80511 non-null  object
 13  Lineitem quantity            80511 non-null  int64
 14  Lineitem name                80511 non-null  object
 15  Lineitem price               80511 non-null  float64
 16  Lineitem compare at price    54219 non-null  float64
 17  Lineitem sku                 78634 non-null  object
 18  Lineitem requires shipping   80511 non-null  bool
 19  Lineitem taxable             80511 non-null  bool
 20  Lineitem fulfillment status  80511 non-null  object
 21  Billing City                 24053 non-null  object
 22  Billing Zip                  14452 non-null  object
 23  Billing Province             24683 non-null  object
 24  Billing Country              24849 non-null  object
 25  Shipping City                24111 non-null  object
 26  Shipping Province            24741 non-null  object
 27  Shipping Country             24868 non-null  object
 28  Cancelled at                 3361 non-null   object
 29  Payment Method               24738 non-null  object
 30  Refunded Amount              24894 non-null  float64
 31  Tags                         13428 non-null  object
 32  Risk Level                   24894 non-null  object
 33  Source                       24894 non-null  object
 34  Lineitem discount            80511 non-null  float64
 35  Tax 1 Name                   0 non-null      float64
 36  Tax 1 Value                  0 non-null      float64
 37  Tax 2 Name                   0 non-null      float64
 38  Tax 2 Value                  0 non-null      float64
 39  Tax 3 Name                   0 non-null      float64
 40  Tax 3 Value                  0 non-null      float64
 41  Tax 4 Name                   0 non-null      float64
 42  Tax 4 Value                  0 non-null      float64
 43  Tax 5 Name                   0 non-null      float64
 44  Tax 5 Value                  0 non-null      float64
 45  Duties                       0 non-null      float64
 46  Billing Province Name        24683 non-null  object
 47  Shipping Province Name       24741 non-null  object
dtypes: bool(2), float64(20), int64(1), object(25)
memory usage: 28.4+ MB

In [4]:
df.describe()

,Subtotal,Shipping,Taxes,Total,Discount Amount,Lineitem quantity,Lineitem price,Lineitem compare at price,Refunded Amount,Lineitem discount,...,Tax 1 Value,Tax 2 Name,Tax 2 Value,Tax 3 Name,Tax 3 Value,Tax 4 Name,Tax 4 Value,Tax 5 Name,Tax 5 Value,Duties
count,24894.000000,24894.000000,24894.0,24894.000000,24894.000000,80511.000000,80511.000000,54219.000000,24894.000000,80511.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,1800.314196,44.305841,0.0,1844.648156,426.802867,1.379700,572.448623,594.279383,18.398876,126.960674,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2157.777693,45.789890,0.0,2151.154461,1064.760566,1.147936,607.131281,864.102863,216.012285,380.948653,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,615.000000,0.000000,0.0,660.000000,0.000000,1.000000,200.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1189.000000,50.000000,0.0,1210.000000,0.000000,1.000000,372.000000,285.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2200.000000,60.000000,0.0,2230.000000,400.000000,1.000000,700.000000,730.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,54091.000000,703.000000,0.0,54091.000000,55837.340000,100.000000,15602.740000,15602.740000,10150.000000,11467.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
columns = df.columns[df.notna().sum() == 0]
columns

Index(['Tax 1 Name', 'Tax 1 Value', 'Tax 2 Name', 'Tax 2 Value', 'Tax 3 Name',
       'Tax 3 Value', 'Tax 4 Name', 'Tax 4 Value', 'Tax 5 Name', 'Tax 5 Value',
       'Duties'],
      dtype='object')

In [8]:
df.drop(columns, axis=1, inplace=True)

In [7]:
columns = df.columns[df.notna().sum() == 0]
columns

Index([], dtype='object')

In [9]:
billing_columns = df.columns[df.columns.str.contains('Billing')]
billing_columns

Index(['Billing City', 'Billing Zip', 'Billing Province', 'Billing Country',
       'Billing Province Name'],
      dtype='object')

In [10]:
df.drop(billing_columns, axis=1, inplace=True)

In [11]:
billing_columns = df.columns[df.columns.str.contains('Billing')]
billing_columns

Index([], dtype='object')

In [12]:
columns_to_drop = ['Source','Risk Level','Tags','Shipping Country','Shipping City','Lineitem fulfillment status','Lineitem taxable','Lineitem requires shipping','Taxes','Currency','Fulfilled at','Fulfillment Status','Paid at','Financial Status']

df.drop(columns_to_drop, axis=1, inplace=True)

In [13]:
df.columns

Index(['Name', 'Subtotal', 'Shipping', 'Total', 'Discount Amount',
       'Shipping Method', 'Created at', 'Lineitem quantity', 'Lineitem name',
       'Lineitem price', 'Lineitem compare at price', 'Lineitem sku',
       'Shipping Province', 'Cancelled at', 'Payment Method',
       'Refunded Amount', 'Lineitem discount', 'Shipping Province Name'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80511 entries, 0 to 80510
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       80511 non-null  object
 1   Subtotal                   24894 non-null  float64
 2   Shipping                   24894 non-null  float64
 3   Total                      24894 non-null  float64
 4   Discount Amount            24894 non-null  float64
 5   Shipping Method            23678 non-null  object
 6   Created at                 80511 non-null  object
 7   Lineitem quantity          80511 non-null  int64
 8   Lineitem name              80511 non-null  object
 9   Lineitem price             80511 non-null  float64
 10  Lineitem compare at price  54219 non-null  float64
 11  Lineitem sku               78634 non-null  object
 12  Shipping Province          24741 non-null  object
 13  Cancelled at               3361 non-null   object
 14  Payment Method             24738 non-null  object
 15  Refunded Amount            24894 non-null  float64
 16  Lineitem discount          80511 non-null  float64
 17  Shipping Province Name     24741 non-null  object
dtypes: float64(8), int64(1), object(9)
memory usage: 11.1+ MB

In [16]:
df.isnull().sum()

Name                             0
Subtotal                         0
Shipping                         0
Total                            0
Discount Amount                  0
Shipping Method                  0
Created at                       0
Lineitem quantity                0
Lineitem name                    0
Lineitem price                   0
Lineitem compare at price    26292
Lineitem sku                  1877
Shipping Province                0
Cancelled at                 77150
Payment Method                   0
Refunded Amount              55617
Lineitem discount                0
Shipping Province Name           0
dtype: int64

In [18]:
df['Lineitem compare at price'] = df['Lineitem compare at price'].fillna(0)
df['Lineitem compare at price'].isnull().sum()

np.int64(0)

In [17]:
df[df['Lineitem sku'].isnull()]

,Name,Subtotal,Shipping,Total,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Shipping Province,Cancelled at,Payment Method,Refunded Amount,Lineitem discount,Shipping Province Name
2282,#MC40007,6230.0,60.0,6290.0,0.00,shipping,2025-01-12 07:45:44 +0200,2,Plain Fitted Bedsheets 200TC,700.0,NaN,NaN,GZ,NaN,Cash on Delivery (COD),NaN,0.0,Giza
6368,#MC38415,6570.0,0.0,6570.0,0.00,Free Shipping,2024-12-01 18:28:22 +0200,1,Mattress Protector 200*200 - Grey,1500.0,NaN,NaN,C,NaN,Cash on Delivery (COD),NaN,0.0,Cairo
6508,#MC38374,2800.0,0.0,2800.0,1200.00,Free Shipping,2024-12-01 12:19:17 +0200,1,Mattress Protector 200*200 - White,1500.0,0.0,NaN,C,NaN,Cash on Delivery (COD),NaN,0.0,Cairo
7993,#MC37837,4215.0,0.0,4215.0,1665.00,Free Shipping,2024-11-29 06:50:41 +0200,1,Mattress Protector 200*200 - Grey,1500.0,NaN,NaN,C,NaN,Cash on Delivery (COD),NaN,0.0,Cairo
8663,#MC37613,5173.0,0.0,5173.0,3600.00,Free Shipping,2024-11-26 09:43:12 +0200,1,Mattress Protector 200*200 - White,1500.0,NaN,NaN,C,NaN,Cash on Delivery (COD),NaN,1500.0,Cairo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79738,#MC14267,2217.0,0.0,2217.0,1238.98,Free Shipping,2022-11-18 12:45:48 +0200,1,Comfort Bundle 4,1234.0,1365.0,NaN,GZ,NaN,Cash on Delivery (COD),NaN,0.0,Giza
79780,#MC14255,999.0,0.0,999.0,1329.97,Free Shipping,2022-11-16 22:11:15 +0200,1,Jacquard Style Bundle,999.0,1330.0,NaN,C,NaN,Cash on Delivery (COD),0.0,0.0,Cairo
79868,#MC14226,1999.0,0.0,1999.0,2400.00,Free Shipping,2022-11-14 17:41:43 +0200,1,Shower Bundle,1999.0,2400.0,NaN,C,NaN,Cash on Delivery (COD),0.0,0.0,Cairo
79882,#MC14223,490.0,50.0,540.0,589.98,Shipping Rate,2022-11-14 15:01:11 +0200,1,Kids Bath Bundle 1,490.0,590.0,NaN,GZ,NaN,Cash on Delivery (COD),0.0,0.0,Giza
79918,#MC14209,1632.0,0.0,1632.0,1504.98,Free Shipping,2022-11-13 11:13:25 +0200,1,Comfort Bundle 4,1234.0,1365.0,NaN,C,NaN,Cash on Delivery (COD),0.0,0.0,Cairo

In [19]:
# Create a dictionary to map Lineitem name to Lineitem sku
sku_mapping = df.dropna(subset=['Lineitem sku']).set_index('Lineitem name')['Lineitem sku'].to_dict()

# Fill missing Lineitem sku values using the mapping
df['Lineitem sku'] = df.apply(
    lambda row: sku_mapping[row['Lineitem name']] if pd.isnull(row['Lineitem sku']) and row['Lineitem name'] in sku_mapping else row['Lineitem sku'],
    axis=1
)

# Verify if there are any remaining missing values in Lineitem sku
df['Lineitem sku'].isnull().sum()

np.int64(1458)

In [22]:
df[df['Lineitem sku'].isnull()]

,Name,Subtotal,Shipping,Total,Discount Amount,Shipping Method,Created at,Lineitem quantity,Lineitem name,Lineitem price,Lineitem compare at price,Lineitem sku,Shipping Province,Cancelled at,Payment Method,Refunded Amount,Lineitem discount,Shipping Province Name
2282,#MC40007,6230.0,60.0,6290.0,0.00,shipping,2025-01-12 07:45:44 +0200,2,Plain Fitted Bedsheets 200TC,700.0,0.0,NaN,GZ,NaN,Cash on Delivery (COD),NaN,0.0,Giza
6368,#MC38415,6570.0,0.0,6570.0,0.00,Free Shipping,2024-12-01 18:28:22 +0200,1,Mattress Protector 200*200 - Grey,1500.0,0.0,NaN,C,NaN,Cash on Delivery (COD),NaN,0.0,Cairo
6508,#MC38374,2800.0,0.0,2800.0,1200.00,Free Shipping,2024-12-01 12:19:17 +0200,1,Mattress Protector 200*200 - White,1500.0,0.0,NaN,C,NaN,Cash on Delivery (COD),NaN,0.0,Cairo
7993,#MC37837,4215.0,0.0,4215.0,1665.00,Free Shipping,2024-11-29 06:50:41 +0200,1,Mattress Protector 200*200 - Grey,1500.0,0.0,NaN,C,NaN,Cash on Delivery (COD),NaN,0.0,Cairo
8663,#MC37613,5173.0,0.0,5173.0,3600.00,Free Shipping,2024-11-26 09:43:12 +0200,1,Mattress Protector 200*200 - White,1500.0,0.0,NaN,C,NaN,Cash on Delivery (COD),NaN,1500.0,Cairo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79738,#MC14267,2217.0,0.0,2217.0,1238.98,Free Shipping,2022-11-18 12:45:48 +0200,1,Comfort Bundle 4,1234.0,1365.0,NaN,GZ,NaN,Cash on Delivery (COD),NaN,0.0,Giza
79780,#MC14255,999.0,0.0,999.0,1329.97,Free Shipping,2022-11-16 22:11:15 +0200,1,Jacquard Style Bundle,999.0,1330.0,NaN,C,NaN,Cash on Delivery (COD),0.0,0.0,Cairo
79868,#MC14226,1999.0,0.0,1999.0,2400.00,Free Shipping,2022-11-14 17:41:43 +0200,1,Shower Bundle,1999.0,2400.0,NaN,C,NaN,Cash on Delivery (COD),0.0,0.0,Cairo
79882,#MC14223,490.0,50.0,540.0,589.98,Shipping Rate,2022-11-14 15:01:11 +0200,1,Kids Bath Bundle 1,490.0,590.0,NaN,GZ,NaN,Cash on Delivery (COD),0.0,0.0,Giza
79918,#MC14209,1632.0,0.0,1632.0,1504.98,Free Shipping,2022-11-13 11:13:25 +0200,1,Comfort Bundle 4,1234.0,1365.0,NaN,C,NaN,Cash on Delivery (COD),0.0,0.0,Cairo

In [24]:
df['Lineitem sku'] = df['Lineitem sku'].fillna('Unknown')
df['Lineitem sku'].isnull().sum()

np.int64(0)

In [28]:
le = LabelEncoder()
le.fit_transform(df['Lineitem name'])
df['Lineitem sku_made'] = le.transform(df['Lineitem name'])

In [31]:
df['Cancelled at'] = df['Cancelled at'].fillna('Not Cancelled')
df['Cancelled at'].isnull().sum()

np.int64(0)

In [32]:
df['Refunded Amount'] = df['Refunded Amount'].fillna(0)
df['Refunded Amount'].isnull().sum()

np.int64(0)

In [34]:
df.isnull().sum()

Name                         0
Subtotal                     0
Shipping                     0
Total                        0
Discount Amount              0
Shipping Method              0
Created at                   0
Lineitem quantity            0
Lineitem name                0
Lineitem price               0
Lineitem compare at price    0
Lineitem sku                 0
Shipping Province            0
Cancelled at                 0
Payment Method               0
Refunded Amount              0
Lineitem discount            0
Shipping Province Name       0
Lineitem sku_made            0
dtype: int64

In [ ]:
# Forward-fill order-level details
order_columns = ["Subtotal", "Shipping", "Total", "Discount Amount", "Shipping Method",
                 "Shipping Province", "Shipping Province Name", "Payment Method", "Created at"]
df[order_columns] = df[order_columns].fillna(method="ffill")

# Group by Order ID, concatenating item names and quantities
df_grouped = df.groupby("Name").agg({
    "Created at": "first",  # Take the first value
    "Subtotal": "first",
    "Shipping": "first",
    "Total": "first",
    "Discount Amount": "first",
    "Shipping Method": "first",
    "Shipping Province": "first",
    "Shipping Province Name": "first",
    "Payment Method": "first",
    "Lineitem name": lambda x: ", ".join(x),  # Join all items into one column
    "Lineitem price": lambda x: ", ".join(map(str, x)),  # Join all prices
    "Lineitem compare at price": lambda x: ", ".join(map(str, x)),  # Join all compare at prices
    "Lineitem sku": lambda x: ", ".join(map(str, x)),  # Join all SKUs
    "Lineitem sku_made": lambda x: ", ".join(map(str, x)),  # Join all SKUs
    "Lineitem quantity": lambda x: ", ".join(map(str, x)), # Join all quantities
    "Lineitem discount": lambda x: ", ".join(map(str, x)),  # Join all discounts
    "Cancelled at": "first",
    "Refunded Amount": "first"
}).reset_index()

# df_grouped.to_csv("depi_grouped.csv", index=False)

/var/folders/rd/rm1ghq0950j6l712s6ykcc5w0000gn/T/ipykernel_78572/301656858.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[order_columns] = df[order_columns].fillna(method="ffill")